/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cline_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_flip CASADI_PREFIX(flip)
#define casadi_interpn CASADI_PREFIX(interpn)
#define casadi_interpn_interpolate CASADI_PREFIX(interpn_interpolate)
#define casadi_interpn_weights CASADI_PREFIX(interpn_weights)
#define casadi_low CASADI_PREFIX(low)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_interpn_weights(casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* x, casadi_real* alpha, casadi_int* index, const casadi_int* lookup_mode) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    casadi_int ng, j;
    casadi_real xi;
    const casadi_real* g;
    xi = x ? x[i] : 0;
    g = grid + offset[i];
    ng = offset[i+1]-offset[i];
    j = index[i] = casadi_low(xi, g, ng, lookup_mode[i]);
    alpha[i] = (xi-g[j])/(g[j+1]-g[j]);
  }
}

void casadi_interpn_interpolate(casadi_real* res, casadi_int ndim, const casadi_int* offset, const casadi_real* values, const casadi_real* alpha, const casadi_int* index, const casadi_int* corner, casadi_real* coeff, casadi_int m) {
  casadi_real c;
  casadi_int ld, i;
  c=1;
  ld=1;
  for (i=0; i<ndim; ++i) {
    if (coeff) *coeff++ = c;
    if (corner[i]) {
      c *= alpha[i];
    } else {
      c *= 1-alpha[i];
    }
    values += (index[i]+corner[i])*ld*m;
    ld *= offset[i+1]-offset[i];
  }
  if (coeff) {
    for (i=0;i<m;++i) res[i] += values[i];
  } else {
    for (i=0;i<m;++i) res[i] += c*values[i];
  }
}

casadi_int casadi_flip(casadi_int* corner, casadi_int ndim) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    if (corner[i]) {
      corner[i]=0;
    } else {
      corner[i]=1;
      return 1;
    }
  }
  return 0;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_interpn(casadi_real* res, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real* alpha;
  casadi_int *index, *corner;
  alpha = w; w += ndim;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(res, m);
  do {
    casadi_real* coeff = 0;
    casadi_interpn_interpolate(res, ndim, offset, values,
      alpha, index, corner, coeff, m);
  } while (casadi_flip(corner, ndim));
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[2] = {0, 40};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};

static const casadi_real casadi_c0[40] = 
  {0., 3.0998796749114992e+00, 3.0994393825531006e+00, 5.9585046768188477e+00, 9.9042406082153320e+00, 1.3509368896484375e+01, 1.7142054557800293e+01, 2.0030118942260742e+01,
  2.2728489875793457e+01, 2.4051939964294434e+01, 2.6243389129638672e+01, 2.7234039306640625e+01, 2.8748539924621582e+01, 2.9040488243103027e+01, 2.8852489471435547e+01, 2.7933990478515625e+01,
  2.7101888656616211e+01, 2.5429189682006836e+01, 2.3177888870239258e+01, 2.0266504287719727e+01, 1.7757965087890625e+01, 1.3424534797668457e+01, 9.7203245162963867e+00, 6.1603744029998779e+00,
  3.3402044773101807e+00, 4.4359457492828369e-01, -9.8790040612220764e-01, -3.2484104335308075e+00, -4.1385104358196259e+00, -6.0367105305194855e+00, -6.3877105116844177e+00, -6.5481104254722595e+00,
  -6.2803103923797607e+00, -5.8649105131626129e+00, -5.5662104189395905e+00, -5.5946104973554611e+00, -4.4704103767871857e+00, -3.7026604712009430e+00, -2.4871104285120964e+00, 0.};
static const casadi_real casadi_c1[40] = 
  {0., 3.1000028202247476e+00, 3.1120621091334995e+00, 5.9763772242997550e+00, 9.9231225264813432e+00, 1.3546826691122758e+01, 1.7347109752269542e+01, 2.0400685560034432e+01,
  2.3315578610639079e+01, 2.4666080084705630e+01, 2.7005814534248145e+01, 2.8325940018561543e+01, 3.0873842259248669e+01, 3.2355617638184206e+01, 3.5626899062454235e+01, 3.8604480324506142e+01,
  4.0871181554606274e+01, 4.3773091152630961e+01, 4.6611001500961919e+01, 4.9862568824947026e+01, 5.2757084499691715e+01, 5.7604068365674372e+01, 6.1745534628956953e+01, 6.5843429952343641e+01,
  6.9202104920866901e+01, 7.2211051404345710e+01, 7.3665011108891278e+01, 7.6312761212532877e+01, 7.7526019894451053e+01, 8.0616983057071451e+01, 8.4002611820359476e+01, 8.5216139466125128e+01,
  8.8097725319127548e+01, 9.0725837187446572e+01, 9.3790220179629245e+01, 9.6770060376439119e+01, 9.9565284794199684e+01, 1.0088400000693478e+02, 1.0216001817176932e+02, 1.0475797893910486e+02};
static const casadi_real casadi_c2[40] = 
  {4.9999999999999989e-01, 4.7236874103546134e-01, 4.6031749248504639e-01, 6.3365739583969116e-01, 5.4440248012542725e-01, 9.1084742546081543e-01, 2.0269774496555328e+00, 3.0186474174261093e+00,
  4.1210973262786865e+00, 3.8521473407745361e+00, 3.0324474871158600e+00, 2.1598974764347076e+00, 1.1097246408462524e-01, -1.3417575359344482e+00, -4.6076323986053467e+00, -7.4400076866149902e+00,
  -9.5484528541564941e+00, -1.1919772624969482e+01, -1.3647597789764404e+01, -1.5095537662506104e+01, -1.6539647102355957e+01, -1.8710968017578125e+01, -2.0563147544860840e+01, -2.2592803001403809e+01,
  -2.4416902542114258e+01, -2.5231402397155762e+01, -2.4976802825927734e+01, -2.3598153114318848e+01, -2.2773702621459961e+01, -2.0334258079528809e+01, -1.6966873168945312e+01, -1.5763992786407471e+01,
  -1.2894877910614014e+01, -1.0299802780151367e+01, -7.2500123977661133e+00, -4.2703075408935547e+00, -1.7111175060272217e+00, -6.3893753290176392e-01, -2.5078749656677246e-01, 4.9999999999999989e-01};

/* xinterp:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c1, casadi_s1, casadi_c0, arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* yinterp:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c1, casadi_s1, casadi_c2, arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* centerline:(i0)->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0]? arg[0][0] : 0;
  a1=5.2378989469552430e+01;
  a2=(a0-a1);
  a3=1.0475797893910486e+02;
  a2=fmod(a2,a3);
  a2=(a2+a1);
  arg[1]=w+0;
  res[1]=w+1;
  w[0] = a2;
  if (casadi_f1(arg+1, res+1, iw, w+2, 0)) return 1;
  a3 = w[1];
  if (res[0]!=0) res[0][0]=a3;
  arg[1]=w+0;
  res[1]=w+1;
  w[0] = a2;
  if (casadi_f2(arg+1, res+1, iw, w+2, 0)) return 1;
  a2 = w[1];
  if (res[0]!=0) res[0][1]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int centerline(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int centerline_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int centerline_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centerline_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int centerline_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centerline_release(int mem) {
}

CASADI_SYMBOL_EXPORT void centerline_incref(void) {
}

CASADI_SYMBOL_EXPORT void centerline_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int centerline_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int centerline_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real centerline_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centerline_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centerline_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centerline_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centerline_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int centerline_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 4;
  return 0;
}

CASADI_SYMBOL_EXPORT int centerline_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 4*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
