/* This file was automatically generated by CasADi 3.7.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) out_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};

/* F:(i0[5],i1[2])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=arg[0]? arg[0][0] : 0;
  a01=3.3333333333333335e-03;
  a02=arg[0]? arg[0][3] : 0;
  a03=arg[0]? arg[0][2] : 0;
  a04=5.0000000000000000e-01;
  a05=arg[0]? arg[0][4] : 0;
  a06=tanh(a05);
  a06=tan(a06);
  a06=(a04*a06);
  a06=atan(a06);
  a07=(a03+a06);
  a07=cos(a07);
  a07=(a02*a07);
  a07=(a01*a07);
  a08=2.;
  a09=arg[1]? arg[1][0] : 0;
  a10=6.1333333333333327e-03;
  a11=casadi_sign(a02);
  a11=(a10*a11);
  a12=casadi_sq(a02);
  a11=(a11*a12);
  a11=(a09-a11);
  a11=(a01*a11);
  a12=(a01*a11);
  a12=(a12/a08);
  a12=(a02+a12);
  a13=7.9000000000000004e-01;
  a14=(a02/a13);
  a15=sin(a06);
  a14=(a14*a15);
  a14=(a01*a14);
  a15=(a01*a14);
  a15=(a15/a08);
  a15=(a03+a15);
  a16=arg[1]? arg[1][1] : 0;
  a17=(a01*a16);
  a18=(a01*a17);
  a18=(a18/a08);
  a18=(a05+a18);
  a18=tanh(a18);
  a18=tan(a18);
  a18=(a04*a18);
  a18=atan(a18);
  a19=(a15+a18);
  a19=cos(a19);
  a19=(a12*a19);
  a19=(a01*a19);
  a19=(a08*a19);
  a07=(a07+a19);
  a19=casadi_sign(a12);
  a19=(a10*a19);
  a20=casadi_sq(a12);
  a19=(a19*a20);
  a19=(a09-a19);
  a19=(a01*a19);
  a20=(a01*a19);
  a20=(a20/a08);
  a20=(a02+a20);
  a21=(a12/a13);
  a22=sin(a18);
  a21=(a21*a22);
  a21=(a01*a21);
  a22=(a01*a21);
  a22=(a22/a08);
  a22=(a03+a22);
  a23=(a01*a16);
  a24=(a01*a23);
  a24=(a24/a08);
  a24=(a05+a24);
  a24=tanh(a24);
  a24=tan(a24);
  a24=(a04*a24);
  a24=atan(a24);
  a25=(a22+a24);
  a25=cos(a25);
  a25=(a20*a25);
  a25=(a01*a25);
  a25=(a08*a25);
  a07=(a07+a25);
  a25=casadi_sign(a20);
  a25=(a10*a25);
  a26=casadi_sq(a20);
  a25=(a25*a26);
  a25=(a09-a25);
  a25=(a01*a25);
  a26=(a01*a25);
  a26=(a02+a26);
  a27=(a20/a13);
  a28=sin(a24);
  a27=(a27*a28);
  a27=(a01*a27);
  a28=(a01*a27);
  a28=(a03+a28);
  a29=(a01*a16);
  a30=(a01*a29);
  a30=(a05+a30);
  a30=tanh(a30);
  a30=tan(a30);
  a30=(a04*a30);
  a30=atan(a30);
  a31=(a28+a30);
  a31=cos(a31);
  a31=(a26*a31);
  a31=(a01*a31);
  a07=(a07+a31);
  a31=6.;
  a07=(a07/a31);
  a00=(a00+a07);
  a19=(a08*a19);
  a11=(a11+a19);
  a25=(a08*a25);
  a11=(a11+a25);
  a25=casadi_sign(a26);
  a25=(a10*a25);
  a19=casadi_sq(a26);
  a25=(a25*a19);
  a25=(a09-a25);
  a25=(a01*a25);
  a11=(a11+a25);
  a11=(a11/a31);
  a11=(a02+a11);
  a21=(a08*a21);
  a14=(a14+a21);
  a27=(a08*a27);
  a14=(a14+a27);
  a27=(a26/a13);
  a21=sin(a30);
  a27=(a27*a21);
  a27=(a01*a27);
  a14=(a14+a27);
  a14=(a14/a31);
  a14=(a03+a14);
  a23=(a08*a23);
  a17=(a17+a23);
  a29=(a08*a29);
  a17=(a17+a29);
  a29=(a01*a16);
  a17=(a17+a29);
  a17=(a17/a31);
  a05=(a05+a17);
  a17=tanh(a05);
  a17=tan(a17);
  a17=(a04*a17);
  a17=atan(a17);
  a29=(a14+a17);
  a29=cos(a29);
  a29=(a11*a29);
  a29=(a01*a29);
  a23=casadi_sign(a11);
  a23=(a10*a23);
  a27=casadi_sq(a11);
  a23=(a23*a27);
  a23=(a09-a23);
  a23=(a01*a23);
  a27=(a01*a23);
  a27=(a27/a08);
  a27=(a11+a27);
  a21=(a11/a13);
  a25=sin(a17);
  a21=(a21*a25);
  a21=(a01*a21);
  a25=(a01*a21);
  a25=(a25/a08);
  a25=(a14+a25);
  a19=(a01*a16);
  a07=(a01*a19);
  a07=(a07/a08);
  a07=(a05+a07);
  a07=tanh(a07);
  a07=tan(a07);
  a07=(a04*a07);
  a07=atan(a07);
  a32=(a25+a07);
  a32=cos(a32);
  a32=(a27*a32);
  a32=(a01*a32);
  a32=(a08*a32);
  a29=(a29+a32);
  a32=casadi_sign(a27);
  a32=(a10*a32);
  a33=casadi_sq(a27);
  a32=(a32*a33);
  a32=(a09-a32);
  a32=(a01*a32);
  a33=(a01*a32);
  a33=(a33/a08);
  a33=(a11+a33);
  a34=(a27/a13);
  a35=sin(a07);
  a34=(a34*a35);
  a34=(a01*a34);
  a35=(a01*a34);
  a35=(a35/a08);
  a35=(a14+a35);
  a36=(a01*a16);
  a37=(a01*a36);
  a37=(a37/a08);
  a37=(a05+a37);
  a37=tanh(a37);
  a37=tan(a37);
  a37=(a04*a37);
  a37=atan(a37);
  a38=(a35+a37);
  a38=cos(a38);
  a38=(a33*a38);
  a38=(a01*a38);
  a38=(a08*a38);
  a29=(a29+a38);
  a38=casadi_sign(a33);
  a38=(a10*a38);
  a39=casadi_sq(a33);
  a38=(a38*a39);
  a38=(a09-a38);
  a38=(a01*a38);
  a39=(a01*a38);
  a39=(a11+a39);
  a40=(a33/a13);
  a41=sin(a37);
  a40=(a40*a41);
  a40=(a01*a40);
  a41=(a01*a40);
  a41=(a14+a41);
  a42=(a01*a16);
  a43=(a01*a42);
  a43=(a05+a43);
  a43=tanh(a43);
  a43=tan(a43);
  a43=(a04*a43);
  a43=atan(a43);
  a44=(a41+a43);
  a44=cos(a44);
  a44=(a39*a44);
  a44=(a01*a44);
  a29=(a29+a44);
  a29=(a29/a31);
  a00=(a00+a29);
  a32=(a08*a32);
  a23=(a23+a32);
  a38=(a08*a38);
  a23=(a23+a38);
  a38=casadi_sign(a39);
  a38=(a10*a38);
  a32=casadi_sq(a39);
  a38=(a38*a32);
  a38=(a09-a38);
  a38=(a01*a38);
  a23=(a23+a38);
  a23=(a23/a31);
  a23=(a11+a23);
  a34=(a08*a34);
  a21=(a21+a34);
  a40=(a08*a40);
  a21=(a21+a40);
  a40=(a39/a13);
  a34=sin(a43);
  a40=(a40*a34);
  a40=(a01*a40);
  a21=(a21+a40);
  a21=(a21/a31);
  a21=(a14+a21);
  a36=(a08*a36);
  a19=(a19+a36);
  a42=(a08*a42);
  a19=(a19+a42);
  a42=(a01*a16);
  a19=(a19+a42);
  a19=(a19/a31);
  a05=(a05+a19);
  a19=tanh(a05);
  a19=tan(a19);
  a19=(a04*a19);
  a19=atan(a19);
  a42=(a21+a19);
  a42=cos(a42);
  a42=(a23*a42);
  a42=(a01*a42);
  a36=casadi_sign(a23);
  a36=(a10*a36);
  a40=casadi_sq(a23);
  a36=(a36*a40);
  a36=(a09-a36);
  a36=(a01*a36);
  a40=(a01*a36);
  a40=(a40/a08);
  a40=(a23+a40);
  a34=(a23/a13);
  a38=sin(a19);
  a34=(a34*a38);
  a34=(a01*a34);
  a38=(a01*a34);
  a38=(a38/a08);
  a38=(a21+a38);
  a32=(a01*a16);
  a29=(a01*a32);
  a29=(a29/a08);
  a29=(a05+a29);
  a29=tanh(a29);
  a29=tan(a29);
  a29=(a04*a29);
  a29=atan(a29);
  a44=(a38+a29);
  a44=cos(a44);
  a44=(a40*a44);
  a44=(a01*a44);
  a44=(a08*a44);
  a42=(a42+a44);
  a44=casadi_sign(a40);
  a44=(a10*a44);
  a45=casadi_sq(a40);
  a44=(a44*a45);
  a44=(a09-a44);
  a44=(a01*a44);
  a45=(a01*a44);
  a45=(a45/a08);
  a45=(a23+a45);
  a46=(a40/a13);
  a47=sin(a29);
  a46=(a46*a47);
  a46=(a01*a46);
  a47=(a01*a46);
  a47=(a47/a08);
  a47=(a21+a47);
  a48=(a01*a16);
  a49=(a01*a48);
  a49=(a49/a08);
  a49=(a05+a49);
  a49=tanh(a49);
  a49=tan(a49);
  a49=(a04*a49);
  a49=atan(a49);
  a50=(a47+a49);
  a50=cos(a50);
  a50=(a45*a50);
  a50=(a01*a50);
  a50=(a08*a50);
  a42=(a42+a50);
  a50=casadi_sign(a45);
  a50=(a10*a50);
  a51=casadi_sq(a45);
  a50=(a50*a51);
  a50=(a09-a50);
  a50=(a01*a50);
  a51=(a01*a50);
  a51=(a23+a51);
  a52=(a45/a13);
  a53=sin(a49);
  a52=(a52*a53);
  a52=(a01*a52);
  a53=(a01*a52);
  a53=(a21+a53);
  a54=(a01*a16);
  a55=(a01*a54);
  a55=(a05+a55);
  a55=tanh(a55);
  a55=tan(a55);
  a04=(a04*a55);
  a04=atan(a04);
  a55=(a53+a04);
  a55=cos(a55);
  a55=(a51*a55);
  a55=(a01*a55);
  a42=(a42+a55);
  a42=(a42/a31);
  a00=(a00+a42);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a03=(a03+a06);
  a03=sin(a03);
  a02=(a02*a03);
  a02=(a01*a02);
  a15=(a15+a18);
  a15=sin(a15);
  a12=(a12*a15);
  a12=(a01*a12);
  a12=(a08*a12);
  a02=(a02+a12);
  a22=(a22+a24);
  a22=sin(a22);
  a20=(a20*a22);
  a20=(a01*a20);
  a20=(a08*a20);
  a02=(a02+a20);
  a28=(a28+a30);
  a28=sin(a28);
  a26=(a26*a28);
  a26=(a01*a26);
  a02=(a02+a26);
  a02=(a02/a31);
  a00=(a00+a02);
  a14=(a14+a17);
  a14=sin(a14);
  a11=(a11*a14);
  a11=(a01*a11);
  a25=(a25+a07);
  a25=sin(a25);
  a27=(a27*a25);
  a27=(a01*a27);
  a27=(a08*a27);
  a11=(a11+a27);
  a35=(a35+a37);
  a35=sin(a35);
  a33=(a33*a35);
  a33=(a01*a33);
  a33=(a08*a33);
  a11=(a11+a33);
  a41=(a41+a43);
  a41=sin(a41);
  a39=(a39*a41);
  a39=(a01*a39);
  a11=(a11+a39);
  a11=(a11/a31);
  a00=(a00+a11);
  a19=(a21+a19);
  a19=sin(a19);
  a19=(a23*a19);
  a19=(a01*a19);
  a38=(a38+a29);
  a38=sin(a38);
  a40=(a40*a38);
  a40=(a01*a40);
  a40=(a08*a40);
  a19=(a19+a40);
  a47=(a47+a49);
  a47=sin(a47);
  a45=(a45*a47);
  a45=(a01*a45);
  a45=(a08*a45);
  a19=(a19+a45);
  a53=(a53+a04);
  a53=sin(a53);
  a53=(a51*a53);
  a53=(a01*a53);
  a19=(a19+a53);
  a19=(a19/a31);
  a00=(a00+a19);
  if (res[0]!=0) res[0][1]=a00;
  a46=(a08*a46);
  a34=(a34+a46);
  a52=(a08*a52);
  a34=(a34+a52);
  a13=(a51/a13);
  a04=sin(a04);
  a13=(a13*a04);
  a13=(a01*a13);
  a34=(a34+a13);
  a34=(a34/a31);
  a21=(a21+a34);
  if (res[0]!=0) res[0][2]=a21;
  a44=(a08*a44);
  a36=(a36+a44);
  a50=(a08*a50);
  a36=(a36+a50);
  a50=casadi_sign(a51);
  a10=(a10*a50);
  a51=casadi_sq(a51);
  a10=(a10*a51);
  a09=(a09-a10);
  a09=(a01*a09);
  a36=(a36+a09);
  a36=(a36/a31);
  a23=(a23+a36);
  if (res[0]!=0) res[0][3]=a23;
  a48=(a08*a48);
  a32=(a32+a48);
  a08=(a08*a54);
  a32=(a32+a08);
  a01=(a01*a16);
  a32=(a32+a01);
  a32=(a32/a31);
  a05=(a05+a32);
  if (res[0]!=0) res[0][4]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
